src/commands/registration/stor.js, src/fs.js
This allows processing of the received data before a response is sent to the client.
=> feat(fs): close stream before ending

src/commands/registration/retr.js, src/commands/registration/stor.js, test/index.spec.js
This should ensure that the errors are handled correctly whether coming from the socket or stream.
=> Improve connector stream handling

src/commands/registration/retr.js
Ensures socket still exists and client hasn't disconnected
=> fix(retr): check for connector socket

ftp-srv.d.ts
Makes `connection`, `root`, and `cwd` in FileSystem class `readonly`.
I believe this is the proper scoping. If any other contributor could let me know if that is correct that would be great 😄.
=> Make FileSystem properties visible

package.json, src/commands/registration/stat.js
Ensures correct response when `stat`-ing a file
```
212-Status begin
...
212 Status end
```
=> fix(stat): fix file response

README.md, src/commands/registration/retr.js, src/commands/registration/stor.js, src/connection.js, src/index.js, test/commands/registration/retr.spec.js, test/commands/registration/stor.spec.js, test/index.spec.js
Server and Connection now extend `EventEmitter`, allowing for custom events on both.
Adds `STOR` and `RETR` events on completion and failure of file upload and download respectively.
=> Emit custom events

ftp-srv.d.ts
Updated TypeScript typings to allow compiling with `noImplicitAny` option enabled in tsconfig.json. Without this change when compiling i see:
```
node_modules/ftp-srv/ftp-srv.d.ts(96,2): error TS7010: 'on', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/ftp-srv/ftp-srv.d.ts(112,2): error TS7010: 'on', which lacks return-type annotation, implicitly has an 'any' return type.
```
=> fix(typings): updated typescript typings

README.md, src/commands/registration/pasv.js, src/connector/passive.js, src/index.js, test/connector/passive.spec.js
This has passive connections to listen on the same hostname as the server.
But allows this to be customized via the `pasv_url` option.
Hostnames are no longer resolved if given `0.0.0.0`, except when being given to the client via `PASV`
https://github.com/trs/ftp-srv/issues/84#issuecomment-392083137
=> feat: pasv_url option to send to client

bin/index.js
cli would reject all logins with `530 Cannot destructure property `password` of 'undefined' or 'null'.` because the credentials object was being indexed with `[object Object]`. Even with that fixed, if the username was not found, it would produce that error.
=> fix(cli): resolve authentication bug

src/commands/registration/retr.js, src/commands/registration/stor.js, src/fs.js, test/fs.spec.js
Emit and reply with the full paths to the files.
BREAKING CHANGE: fs expects an object `{stream, clientPath}` in response to `.read()` and `.write()`.
This is implemented in a backwards compatible way, and works with the old `fs` implementation. But since this may break builds in unintended ways.
Fixes: https://github.com/trs/ftp-srv/issues/90
=> feat: respond with full paths in STOR/RETR

src/connector/passive.js, src/index.js, test/index.spec.js
Fixes an issue where passive TLS connections would never be fulfilled.
This uses `tls` to create a server if the connection is secure instead of upgrading an already connected socket.
Fixes:
- https://github.com/trs/ftp-srv/issues/96
=> fix(connector): build passive server correctly for tls

src/commands/registration/stor.js, src/connector/base.js, src/connector/passive.js
Seemed to be a collection of issues there were all combining to cause this.
1. Use the 'end' event instead of the close event
2. Use the correct events when waiting for a passive connection to be established
3. Dont close the sockets so aggressively
@trs Appreciate a review here, there was a lot of trial and error to get this fix working. You might spot a few improvements
=> (fix): timeouts when using tls

ftp-srv.d.ts
Based on the typings, I first configured tls as follows, which let to a vague error `ssl3_get_client_hello:no shared cipher`:
```javascript
const server = new FtpSrv({
url: process.env.FTP_CONNECTION_STR,
tls: tls.createSecureContext({
key: fs.readFileSync('./cert/server.pem'),
cert: fs.readFileSync('./cert/public-cert.pem'),
}),
});
```
The tls server option doesn't expect `SecureContext`, but `SecureContextOptions` like this:
```javascript
const server = new FtpSrv({
url: process.env.FTP_CONNECTION_STR,
tls: {
key: fs.readFileSync('./cert/server.pem'),
cert: fs.readFileSync('./cert/public-cert.pem'),
},
});
```
=> fix: add correct typing for tls option

src/index.js
The passive url is passed to getNextPortFactory so in passive mode, the
opening of a listening port fail when the passive url is not the ip of
an interface on the ftp server host machine.
=> fix: find available port using hostname

src/commands/registration/list.js, src/connection.js
Prevent FTP clients to crash with an exception, when they use encryption and want to list an empty folder on the FTP server.
=> Listing empty folders sends back a response

package-lock.json, package.json, src/commands/registration/list.js, src/commands/registration/opts.js, src/commands/registration/pasv.js, src/commands/registration/retr.js, src/commands/registration/stor.js, src/connection.js, src/connector/active.js, src/connector/passive.js, src/fs.js, src/helpers/fs-async.js, src/helpers/is-local.js, test/index.spec.js, test/start.js
Includes:
- https://github.com/trs/ftp-srv/pull/160
- https://github.com/trs/ftp-srv/pull/166
Fixes:
- https://github.com/trs/ftp-srv/pull/159
- https://github.com/trs/ftp-srv/issues/149
- https://github.com/trs/ftp-srv/issues/167
=> Various Issue Fixes

ftp-srv.d.ts, src/index.js, test/index.spec.js
This PR adds a `disconnect` event that fires whenever a client is removed from the list of active connections.
Types and tests for this PR are already implemented.
This fixes #174
=> feat: 'disconnect' event

src/commands/registration/opts.js
If an unknown option is given, the response should be 501.
Fixes: https://github.com/trs/ftp-srv/issues/189
=> fix: correct OPTS error code

README.md, package.json, src/commands/index.js, src/commands/registration/feat.js, src/connection.js, src/index.js
- Fixes an issue where the client would never close, hanging the server and preventing shutdown
- Ensures `disconnect` events trigger when connection closes
=>  fix: correctly destroy socket on close 

package-lock.json, package.json, src/commands/registration/stor.js
Correct NPM advisories by updating package-lock.json and package
dependencies.
Major upgrade for yargs, but did not affect our code directly.
=> fix: packages updates - npm advisories

src/commands/registration/stor.js
This PR aim is to make socket pipe method available on `FTP` command `STOR` , in order to support other methods and make it more versatile to support other npm packages like `s3fs`. because of an issue to write the stream directly to `AWS S3`, i decided to allow pipe method on `STOR` command. That may help you to come up with a better solution. also, there was a problem on `sockt.resume` function, which triggers error, if it does not exist probably because the socket is closed. 
Thanks
=> feat: pipe stream on fs write

src/connection.js
IP address of connection is always undefined, as `this.ip` is called before `this.commandSocket` is set, which is what the ip getter relies on for finding the IP address.
=> fix: ensure commandSocket is set before retrieving ip address of connection

src/commands/registration/port.js
Some hardware devices are passing IP address with zeroes padding (e.g 192.168.001.103) to PORT command.
That causes DNS lookup failure on Windows hosts.
```
error: Error: getaddrinfo ENOTFOUND 192.168.001.103
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
errno: 'ENOTFOUND',
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: '192.168.001.103'
}```
=> fix: dns lookup fail with IP with zeros padding

package.json, src/commands/registration/feat.js, test/commands/registration/feat.spec.js
If requiring the registry from the module scope the result is an empty object. I assume this is caused by the circular nature of this dep.
Takes the core fix from https://github.com/autovance/ftp-srv/pull/234 (thank you!)
=> fix(feat): lazy require registry 

README.md
Fixes single character typo in the readme, `tne` => `the`
=> fix small readme typo

README.md, src/commands/registration/pasv.js
Allow passing a function to pasv_url with the remote IP of the client, so that we can flexibly decide what is the correct passive URL to use. Useful if we want an FTP to be used from different networks (Intranet and internet for example)
=> feat: allow dynamic pasv_url depending on remote address

README.md, ftp-srv.d.ts, src/commands/registration/stou.js
Make client requested fileName available on getUniqueName function, to be used optionally if you want for example to use temp filenames adding some suffix on the original name.
=> chore: make fileName available in getUniqueName

src/commands/registration/mkd.js, src/fs.js, test/index.spec.js
The MKD command should be making all the necessary directories when uploading to a directory that doesn't exists yet. 
Previously this wasn't the case, by adding ```{ recursive: true }``` to the ```fs.mkdir``` function this should work correctly now.
NodeJS version 10.12.0 has added a native support for both mkdir and mkdirSync to create a directory recursively with [recursive: true](https://nodejs.org/api/fs.html#fs_fs_mkdirsync_path_options)
=> feat: allow mkd command to create directories recursively

README.md
The example does not show the full login event parameters.
=> docs(readme): update prime login example

README.md, src/index.js
Dear,
Based on my [discussion ](https://github.com/QuorumDMS/ftp-srv/discussions/310) I would like to contribute the following event emitter changes:
+ The existing `disconnect` event has now 1 extra parameter parameter *"newConnectionCount"*, to make it easier to know how much connections are still active (after the disconnect).
+ A new `connect` event has been added, identical to the existing disconnect event.
+ A new `server-error` event has been added, to intercept server-side errors (like e.g. unparsable IP address).
+ A new `closing` event has been added, to know when the server is closing.
+ A new `closed` event has been added, to know when the server has been closed.
Documentation has been added to the readme page for all these new events, and also for the existing `disconnect` …
=> New event emitters (connect, server-error, closing, closed)
