package.json
src/commands/registration/mdtm.js
src/helpers/file-stat.js
test/helpers/file-stat.spec.js

Date-fns is great, but too early for use

feat: migrate to moment from date-fns, fix ls format

---

ftp-srv.d.ts
package.json

* created outline for TypeScript declarations
* added basic object shapes for FtpServer and FileSystem

feat(typings): add TypeScript .d.ts files

---

.travis.yml
package.json

Should ensure types are inluded on an install

fix(package): include types file

---

README.md
package.json

The `main` file was changed when updating with the confit generator.

Fix package main file

---

ftp-srv.d.ts

The current typings don't work with the library in it's current form. I've made some changes to fix this.

Updated TypeScript definition file to something that works

---

package-lock.json
package.json
test/index.spec.js

- Removes `mock-fs` as it was causing issues with mocha

test: update integration tests

---

package.json
src/commands/registration/stat.js

Ensure message is sent raw, without code prefix.

fix(stat): fix stat on file

---

src/commands/registration/retr.js
src/commands/registration/stor.js
test/index.spec.js

See: https://github.com/trs/ftp-srv/pull/67
Thanks to [voxsoftware](https://github.com/voxsoftware)

Pause stream to avoid memory build up

---

src/commands/registration/rest.js

fix(rest): small typo

---

README.md
bin/ftp-srv
package.json

Not sure if I have to add `package-lock.json`.

feat(cli): add cli support for ftp-srv

---

src/helpers/file-stat.js
test/connector/passive.spec.js
test/helpers/file-stat.spec.js

Simple improvements to some fragile tests.

test: fix tests

---

src/fs.js
test/fs.spec.js
test/index.spec.js

Improve file system path resolution for cross platform (windows).
Fixes: https://github.com/trs/ftp-srv/issues/78

fix(fs): improve path resolution 

---

README.md

chore(readme): correct word and improve events

---

README.md

chore(readme): correct word and improve events docs

---

package-lock.json
package.json

Fixes vulnerabilities in packages, removes unused and vulnerable `chokidar-cli` package.

chore(package): update package lock

---

src/connector/base.js

Fixes GnuTLS error -110: The TLS connection was non-properly terminated issue

fix(connector): gracefully end data socket

---

src/commands/index.js

fix: command parse ignores flags on RETR and SIZE

---

.circleci/config.yml
package-lock.json
package.json

Update to latest semantic release, should fix detecting unpublished version.

chore: update semantic-release

---

bin/index.js

Config was not setup correctly after v3 change.

fix(cli): correctly setup server, add pasv options

---

ftp-srv.d.ts

Syncing FtpServerOptions with code.

fix: add pasv_url to typescript definitions

---

bin/index.js

fix(cli): correct  --root flag logic

---

README.md
ftp-srv.d.ts
package-lock.json
src/connection.js
src/index.js

By the nodejs API documentation the Socket object doesn't have a timeout set.
I added a new param socketTimeout (numeric) to pass to the FtpServer so the timeout can be set on the socket created.

feat: socket timeout

---

package-lock.json
package.json
src/commands/registration/stor.js
src/helpers/find-port.js
test/helpers/find-port.spec.js
test/index.spec.js

Creates a new instance of a server each time the port search is called.
This ensures that concurrent calls to this function wont hang or produce
`ERR_SERVER_ALREADY_LISTEN`

fix: enable better concurrent port search

---

README.md

docs: fixes the documentation of pasv_url behaviour

---

src/commands/index.js
test/commands/index.spec.js

Fixes: https://github.com/trs/ftp-srv/issues/184

fix(commands): 502 error on unsupported command

---

README.md
bin/index.js

https://github.com/autovance/ftp-srv/issues/192#issuecomment-671628182

docs: clarify passive options and behaviour

---

.circleci/config.yml
package.json

current release flow doesn't work
improve supported version testing

chore: improve ci flows

---

README.md

This project is very useful to me. Although it provides quick start, it does not help me to use this library. I refer to bin/index.js to continue, so I updated the code in the example.

Provide more friendly example code.

---

.circleci/config.yml
package-lock.json
package.json
src/index.js
test/index.spec.js

- refactor: improve close flow, more accurate logging
- test: correctly clean up recursive dir test
- chore(dependencies): update dev deps, bring security notices to zero
- chore: remove add from lint
BREAKING CHANGE: drop support for node v10 (out of LTS)

feat: npm updates, security zero, test corrections

---

README.md

the ip variable in resolverFunction  is not defined, it is replaced by address which has the correct value

fix pasv_url resolverFunction docs

---

ftp-srv.d.ts

---
- One of:
- changes not related should be moved to a different PR
See changes in #336.

Fix #336, Added errors to typescript declarations

---

src/errors.js

---
- One of:
- changes not related should be moved to a different PR
For more details see #338 .

Fix #338, Parse error message to super constructor
